apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: safarnama
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: wantedmind11/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: BACKEND_URL
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: safarnama-secrets
                  key: GEMINI_API_KEY
